# Generated by Django 4.1.1 on 2022-09-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=150)),
                ('description', models.CharField(max_length=2000)),
                ('done', models.BooleanField()),
            ],
        ),
    ]
