# Generated by Django 4.1.1 on 2022-09-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
