# Generated by Django 4.1.1 on 2022-09-18 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0003_alter_note_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note',
            new_name='title',
        ),
    ]
