# Generated by Django 4.1.1 on 2022-09-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0004_rename_note_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='done',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
